.titanic.ref <- list(titanic.class =
    c("Crew", "1st", "3rd", "Crew", "3rd", "Crew", "1st", "3rd", 
    "1st", "Crew", "Crew", "2nd", "3rd", "3rd", "Crew", "2nd", "Crew", 
    "1st", "3rd", "Crew", "Crew", "3rd", "Crew", "3rd", "3rd", "1st", 
    "3rd", "Crew", "3rd", "Crew", "2nd", "2nd", "1st", "3rd", "Crew", 
    "1st", "1st", "3rd", "1st", "3rd", "Crew", "Crew", "1st", "2nd", 
    "2nd", "3rd", "3rd", "2nd", "1st", "Crew", "1st", "3rd", "Crew", 
    "3rd", "Crew", "3rd", "3rd", "Crew", "Crew", "Crew", "Crew", 
    "1st", "3rd", "Crew", "3rd", "Crew", "3rd", "3rd", "3rd", "3rd", 
    "3rd", "3rd", "3rd", "3rd", "1st", "1st", "Crew", "3rd", "Crew", 
    "Crew", "Crew", "Crew", "Crew", "Crew", "1st", "2nd", "1st", 
    "2nd", "Crew", "1st", "3rd", "3rd", "Crew", "Crew", "Crew", "Crew", 
    "2nd", "3rd", "1st", "3rd", "1st", "1st", "3rd", "Crew", "1st", 
    "1st", "3rd", "Crew", "3rd", "2nd", "3rd", "Crew", "Crew", "3rd", 
    "1st", "Crew", "Crew", "1st", "Crew", "3rd", "Crew", "2nd", "Crew", 
    "3rd", "Crew", "3rd", "Crew", "1st", "Crew", "1st", "2nd", "3rd", 
    "2nd", "1st", "1st", "Crew", "3rd", "3rd", "3rd", "3rd", "3rd", 
    "Crew", "Crew", "Crew", "Crew", "2nd", "Crew", "1st", "Crew", 
    "Crew", "3rd", "Crew", "Crew", "Crew", "3rd", "2nd", "3rd", "3rd", 
    "1st", "3rd", "1st", "3rd", "1st", "3rd", "Crew", "Crew", "Crew", 
    "2nd", "Crew", "Crew", "2nd", "3rd", "3rd", "3rd", "Crew", "Crew", 
    "3rd", "3rd", "3rd", "Crew", "2nd", "3rd", "1st", "3rd", "Crew", 
    "3rd", "Crew", "Crew", "3rd", "Crew", "3rd", "Crew", "Crew", 
    "3rd", "3rd", "3rd", "3rd", "3rd", "2nd", "2nd", "Crew", "Crew", 
    "Crew", "3rd", "2nd", "3rd", "Crew", "2nd", "1st", "2nd", "3rd", 
    "3rd", "2nd", "2nd", "3rd", "2nd", "Crew", "1st", "Crew", "Crew", 
    "Crew", "3rd", "Crew", "Crew", "2nd", "Crew", "3rd", "Crew", 
    "3rd", "Crew", "Crew", "2nd", "Crew", "Crew", "1st", "1st", "2nd", 
    "1st", "3rd", "Crew", "Crew", "3rd", "Crew", "Crew", "3rd", "2nd", 
    "1st", "Crew", "1st", "3rd", "Crew", "Crew", "3rd", "Crew", "1st", 
    "Crew", "3rd", "1st", "Crew", "2nd", "3rd", "3rd", "Crew", "3rd", 
    "2nd", "1st", "Crew", "1st", "3rd", "Crew", "1st", "Crew", "1st", 
    "Crew", "Crew", "Crew", "Crew", "Crew", "2nd", "1st", "Crew", 
    "Crew", "Crew", "1st", "Crew", "Crew", "3rd", "3rd", "Crew", 
    "Crew", "Crew", "Crew", "Crew", "2nd", "Crew", "Crew", "3rd", 
    "Crew", "Crew", "3rd", "2nd", "3rd", "Crew", "3rd", "3rd", "1st", 
    "Crew", "Crew", "2nd", "1st", "Crew", "Crew", "Crew", "Crew", 
    "3rd", "2nd", "3rd", "3rd", "3rd", "Crew", "Crew", "Crew", "3rd", 
    "2nd", "Crew", "3rd", "2nd", "3rd", "Crew", "3rd", "Crew", "1st", 
    "1st", "2nd", "Crew", "1st", "Crew", "Crew", "1st", "3rd", "Crew", 
    "Crew", "Crew", "Crew", "Crew", "Crew", "Crew", "Crew", "3rd", 
    "Crew", "Crew", "3rd", "Crew", "1st", "Crew", "3rd", "3rd", "2nd", 
    "Crew", "3rd", "3rd", "Crew", "Crew", "Crew", "1st", "Crew", 
    "Crew", "Crew", "Crew", "3rd", "3rd", "Crew", "Crew", "2nd", 
    "Crew", "3rd", "3rd", "2nd", "Crew", "2nd", "Crew", "2nd", "3rd", 
    "Crew", "1st", "3rd", "1st", "3rd", "3rd", "Crew", "2nd", "Crew", 
    "3rd", "Crew", "Crew", "1st", "2nd", "1st", "Crew", "Crew", "3rd", 
    "3rd", "3rd", "3rd", "3rd", "3rd", "2nd", "2nd", "Crew", "3rd", 
    "3rd", "Crew", "Crew", "3rd", "Crew", "Crew", "3rd", "1st", "3rd", 
    "1st", "Crew", "1st", "1st", "1st", "3rd", "2nd", "3rd", "3rd", 
    "1st", "2nd", "Crew", "3rd", "2nd", "Crew", "Crew", "Crew", "3rd", 
    "2nd", "Crew", "1st", "Crew", "Crew", "Crew", "Crew", "2nd", 
    "3rd", "Crew", "1st", "Crew", "Crew", "3rd", "2nd", "3rd", "3rd", 
    "Crew", "Crew", "1st", "Crew", "Crew", "Crew", "3rd", "Crew", 
    "1st", "Crew", "Crew", "2nd", "Crew", "2nd", "2nd", "Crew", "Crew", 
    "3rd", "Crew", "Crew", "3rd", "Crew", "Crew", "1st", "3rd", "Crew", 
    "1st", "1st", "1st", "2nd", "3rd", "Crew", "3rd", "Crew", "Crew", 
    "1st", "3rd", "2nd", "Crew", "3rd", "2nd", "Crew", "Crew", "3rd", 
    "1st", "Crew", "3rd", "3rd", "3rd", "3rd", "2nd", "1st", "Crew", 
    "Crew", "Crew", "3rd", "3rd", "Crew", "3rd", "2nd", "Crew", "Crew", 
    "1st", "Crew", "3rd", "2nd", "Crew", "1st", "3rd", "3rd", "1st", 
    "1st", "Crew", "Crew", "Crew", "Crew", "2nd", "Crew", "Crew", 
    "Crew", "Crew", "2nd", "3rd", "3rd", "3rd", "3rd", "3rd", "Crew", 
    "1st", "Crew", "2nd", "2nd", "Crew", "Crew", "Crew", "2nd", "Crew", 
    "3rd", "2nd", "2nd", "3rd", "Crew", "Crew", "Crew", "Crew", "2nd", 
    "Crew", "3rd", "1st", "1st", "Crew", "Crew", "Crew", "3rd", "Crew", 
    "2nd", "Crew", "3rd", "3rd", "Crew", "2nd", "3rd", "Crew", "Crew", 
    "Crew", "2nd", "3rd", "3rd", "3rd", "1st", "Crew", "1st", "1st", 
    "3rd", "3rd", "Crew", "2nd", "Crew", "2nd", "3rd", "1st", "Crew", 
    "3rd", "Crew", "3rd", "Crew", "1st", "Crew", "2nd", "1st", "3rd", 
    "2nd", "Crew", "3rd", "1st", "3rd", "1st", "3rd", "2nd", "2nd", 
    "3rd", "3rd", "2nd", "3rd", "2nd", "1st", "Crew", "2nd", "1st", 
    "3rd", "2nd", "Crew", "Crew", "Crew", "Crew", "3rd", "2nd", "Crew", 
    "3rd", "2nd", "Crew", "2nd", "1st", "3rd", "Crew", "3rd", "1st", 
    "3rd", "3rd", "1st", "1st", "3rd", "3rd", "3rd", "Crew", "Crew", 
    "Crew", "1st", "Crew", "1st", "Crew", "3rd", "2nd", "Crew", "3rd", 
    "3rd", "Crew", "1st", "Crew", "3rd", "2nd", "Crew", "3rd", "Crew", 
    "Crew", "Crew", "3rd", "3rd", "Crew", "2nd", "Crew", "2nd", "Crew", 
    "3rd", "Crew", "Crew", "Crew", "3rd", "Crew", "3rd", "Crew", 
    "3rd", "Crew", "3rd", "Crew", "3rd", "3rd", "Crew", "Crew", "1st", 
    "Crew", "Crew", "1st", "3rd", "3rd", "Crew", "3rd", "3rd", "Crew", 
    "Crew", "Crew", "3rd", "2nd", "3rd", "Crew", "1st", "Crew", "1st", 
    "3rd", "1st", "1st", "Crew", "Crew", "1st", "Crew", "Crew", "2nd", 
    "Crew", "Crew", "Crew", "3rd", "3rd", "3rd", "1st", "Crew", "2nd", 
    "Crew", "3rd", "Crew", "2nd", "Crew", "3rd", "Crew", "1st", "3rd", 
    "Crew", "2nd", "1st", "Crew", "2nd", "3rd", "3rd", "3rd", "Crew", 
    "2nd", "1st", "Crew", "3rd", "Crew", "2nd", "3rd", "Crew", "3rd", 
    "Crew", "2nd", "1st", "1st", "3rd", "1st", "Crew", "3rd", "3rd", 
    "2nd", "Crew", "3rd", "3rd", "Crew", "2nd", "2nd", "Crew", "Crew", 
    "1st", "Crew", "2nd", "3rd", "3rd", "3rd", "1st", "3rd", "1st", 
    "3rd", "3rd", "3rd", "Crew", "3rd", "3rd", "1st", "1st", "Crew", 
    "Crew", "3rd", "3rd", "2nd", "3rd", "Crew", "Crew", "Crew", "3rd", 
    "Crew", "3rd", "Crew", "Crew", "3rd", "3rd", "2nd", "2nd", "2nd", 
    "3rd", "Crew", "3rd", "2nd", "Crew", "Crew", "3rd", "1st", "Crew", 
    "Crew", "1st", "3rd", "Crew", "Crew", "1st", "3rd", "Crew", "3rd", 
    "3rd", "Crew", "Crew", "2nd", "Crew", "1st", "Crew", "3rd", "2nd", 
    "Crew", "3rd", "2nd", "Crew", "3rd", "Crew", "3rd", "3rd", "3rd", 
    "Crew", "Crew", "Crew", "Crew", "Crew", "1st", "Crew", "2nd", 
    "Crew", "3rd", "Crew", "2nd", "1st", "Crew", "3rd", "Crew", "1st", 
    "3rd", "1st", "2nd", "3rd", "3rd", "Crew", "Crew", "Crew", "1st", 
    "3rd", "2nd", "3rd", "3rd", "3rd", "Crew", "Crew", "3rd", "2nd", 
    "Crew", "3rd", "3rd", "1st", "3rd", "Crew", "3rd", "Crew", "1st", 
    "3rd", "3rd", "1st", "Crew", "3rd", "Crew", "3rd", "Crew", "3rd", 
    "2nd", "3rd", "Crew", "Crew", "1st", "Crew", "2nd", "3rd", "2nd", 
    "3rd", "Crew", "1st", "1st", "Crew", "3rd", "1st", "Crew", "3rd", 
    "1st", "2nd", "2nd", "Crew", "3rd", "2nd", "3rd", "Crew", "Crew", 
    "Crew", "3rd", "Crew", "2nd", "3rd", "3rd", "Crew", "Crew", "Crew", 
    "Crew", "1st", "1st", "Crew", "Crew", "1st", "2nd", "1st", "1st", 
    "3rd", "3rd", "Crew", "1st", "Crew", "Crew", "3rd", "2nd", "Crew", 
    "Crew", "1st", "3rd", "Crew", "1st", "Crew", "Crew", "Crew", 
    "3rd", "Crew", "Crew", "3rd", "2nd", "1st", "3rd", "Crew", "Crew", 
    "1st", "Crew", "1st", "1st", "Crew", "3rd", "Crew", "3rd", "Crew", 
    "1st", "3rd", "2nd", "3rd", "1st", "Crew", "Crew", "Crew", "Crew", 
    "2nd", "Crew", "Crew", "Crew", "3rd", "Crew", "2nd", "Crew", 
    "3rd", "3rd", "1st", "1st", "3rd", "3rd", "3rd", "Crew", "Crew", 
    "Crew", "Crew", "1st", "1st", "Crew", "Crew", "3rd", "Crew", 
    "3rd", "3rd", "3rd", "1st", "3rd", "Crew", "3rd", "3rd", "3rd", 
    "Crew", "3rd", "3rd", "2nd", "Crew", "2nd", "Crew", "Crew", "Crew", 
    "Crew", "1st", "3rd", "3rd", "Crew", "1st", "3rd", "1st", "3rd", 
    "Crew", "1st", "3rd", "1st", "2nd", "1st", "Crew", "3rd", "3rd", 
    "Crew", "2nd", "Crew", "Crew", "Crew", "Crew", "1st", "Crew", 
    "1st", "Crew", "3rd", "3rd", "3rd", "2nd", "Crew", "Crew", "Crew", 
    "Crew", "3rd", "3rd", "Crew", "1st", "Crew", "1st", "3rd", "1st", 
    "Crew", "3rd", "1st", "2nd", "2nd", "3rd", "Crew", "3rd", "1st", 
    "1st", "2nd", "1st", "3rd", "3rd", "2nd", "Crew", "Crew", "3rd", 
    "Crew", "3rd", "3rd", "2nd", "Crew", "Crew", "Crew", "2nd", "Crew", 
    "Crew", "Crew", "Crew", "Crew", "Crew", "1st", "Crew", "3rd", 
    "2nd", "2nd", "3rd", "3rd", "3rd", "Crew", "3rd", "1st", "Crew", 
    "2nd", "Crew", "3rd", "Crew", "3rd", "Crew", "2nd", "1st", "3rd", 
    "3rd", "Crew", "Crew", "3rd", "Crew", "Crew", "Crew", "1st", 
    "Crew", "Crew", "Crew", "2nd", "Crew", "3rd", "1st", "Crew", 
    "1st", "1st", "3rd", "3rd", "3rd", "3rd", "3rd", "Crew", "3rd", 
    "3rd", "Crew", "Crew", "3rd", "3rd", "3rd", "1st", "Crew", "3rd", 
    "2nd", "1st", "Crew", "3rd", "Crew", "Crew", "1st", "2nd", "2nd", 
    "Crew", "Crew", "1st", "3rd", "3rd", "Crew", "3rd", "Crew", "3rd", 
    "3rd", "3rd", "Crew", "2nd", "Crew", "Crew", "3rd", "Crew", "3rd", 
    "Crew", "3rd", "2nd", "Crew", "Crew", "3rd", "1st", "3rd", "3rd", 
    "1st", "3rd", "Crew", "2nd", "Crew", "Crew", "1st", "2nd", "Crew", 
    "Crew", "Crew", "3rd", "Crew", "3rd", "Crew", "3rd", "3rd", "Crew", 
    "Crew", "3rd", "1st", "3rd", "3rd", "3rd", "Crew", "3rd", "3rd", 
    "3rd", "3rd", "3rd", "2nd", "3rd", "1st", "3rd", "3rd", "3rd", 
    "2nd", "1st", "1st", "Crew", "3rd", "2nd", "Crew", "3rd", "3rd", 
    "2nd", "3rd", "Crew", "Crew", "3rd", "Crew", "Crew", "Crew", 
    "Crew", "3rd", "1st", "3rd", "Crew", "Crew", "3rd", "Crew", "Crew", 
    "Crew", "3rd", "2nd", "1st", "Crew", "3rd", "Crew", "2nd", "Crew", 
    "Crew", "Crew", "3rd", "Crew", "Crew", "3rd", "2nd", "3rd", "3rd", 
    "2nd", "Crew", "1st", "Crew", "3rd", "1st", "1st", "1st", "Crew", 
    "Crew", "Crew", "Crew", "3rd", "1st", "Crew", "1st", "Crew", 
    "Crew", "Crew", "Crew", "Crew", "Crew", "1st", "3rd", "3rd", 
    "3rd", "3rd", "3rd", "2nd", "2nd", "3rd", "Crew", "Crew", "3rd", 
    "1st", "Crew", "1st", "Crew", "Crew", "Crew", "1st", "2nd", "2nd", 
    "Crew", "Crew", "Crew", "Crew", "Crew", "3rd", "3rd", "3rd", 
    "Crew", "Crew", "1st", "1st", "2nd", "Crew", "3rd", "1st", "Crew", 
    "Crew", "3rd", "2nd", "Crew", "Crew", "2nd", "Crew", "3rd", "1st", 
    "2nd", "3rd", "1st", "Crew", "3rd", "Crew", "3rd", "3rd", "3rd", 
    "Crew", "2nd", "2nd", "3rd", "3rd", "3rd", "Crew", "3rd", "Crew", 
    "3rd", "1st", "3rd", "3rd", "1st", "1st", "1st", "Crew", "3rd", 
    "Crew", "3rd", "3rd", "Crew", "Crew", "2nd", "Crew", "3rd", "Crew", 
    "3rd", "3rd", "3rd", "Crew", "Crew", "1st", "2nd", "1st", "Crew", 
    "2nd", "3rd", "Crew", "2nd", "Crew", "Crew", "3rd", "3rd", "Crew", 
    "3rd", "3rd", "3rd", "Crew", "2nd", "2nd", "3rd", "3rd", "1st", 
    "Crew", "Crew", "Crew", "3rd", "Crew", "2nd", "Crew", "2nd", 
    "Crew", "3rd", "1st", "3rd", "1st", "Crew", "3rd", "Crew", "Crew", 
    "2nd", "Crew", "1st", "3rd", "Crew", "1st", "1st", "1st", "3rd", 
    "2nd", "Crew", "Crew", "3rd", "3rd", "3rd", "3rd", "3rd", "3rd", 
    "Crew", "1st", "Crew", "Crew", "Crew", "2nd", "3rd", "2nd", "Crew", 
    "3rd", "Crew", "3rd", "Crew", "Crew", "Crew", "3rd", "Crew", 
    "3rd", "Crew", "3rd", "2nd", "3rd", "Crew", "Crew", "1st", "Crew", 
    "1st", "Crew", "Crew", "3rd", "3rd", "3rd", "2nd", "Crew", "3rd", 
    "Crew", "Crew", "Crew", "3rd", "2nd", "1st", "3rd", "3rd", "Crew", 
    "2nd", "3rd", "1st", "Crew", "3rd", "3rd", "2nd", "Crew", "Crew", 
    "1st", "Crew", "2nd", "Crew", "1st", "3rd", "3rd", "Crew", "3rd", 
    "Crew", "3rd", "Crew", "Crew", "2nd", "Crew", "3rd", "3rd", "3rd", 
    "1st", "1st", "1st", "3rd", "1st", "3rd", "3rd", "Crew", "3rd", 
    "3rd", "Crew", "Crew", "3rd", "Crew", "2nd", "3rd", "Crew", "Crew", 
    "Crew", "3rd", "1st", "2nd", "Crew", "3rd", "Crew", "Crew", "1st", 
    "Crew", "3rd", "2nd", "3rd", "3rd", "Crew", "1st", "Crew", "Crew", 
    "2nd", "2nd", "Crew", "3rd", "2nd", "3rd", "2nd", "Crew", "3rd", 
    "Crew", "1st", "Crew", "3rd", "2nd", "2nd", "Crew", "Crew", "Crew", 
    "1st", "Crew", "3rd", "3rd", "2nd", "Crew", "3rd", "3rd", "2nd", 
    "Crew", "Crew", "3rd", "3rd", "Crew", "Crew", "1st", "2nd", "Crew", 
    "Crew", "Crew", "1st", "1st", "1st", "Crew", "3rd", "1st", "Crew", 
    "3rd", "Crew", "3rd", "Crew", "2nd", "3rd", "Crew", "3rd", "2nd", 
    "3rd", "3rd", "3rd", "Crew", "Crew", "Crew", "1st", "3rd", "Crew", 
    "1st", "2nd", "1st", "3rd", "Crew", "3rd", "3rd", "3rd", "3rd", 
    "1st", "1st", "3rd", "1st", "Crew", "Crew", "1st", "3rd", "3rd", 
    "3rd", "2nd", "Crew", "1st", "2nd", "Crew", "3rd", "3rd", "Crew", 
    "2nd", "2nd", "3rd", "1st", "3rd", "2nd", "Crew", "Crew", "3rd", 
    "1st", "Crew", "3rd", "Crew", "3rd", "Crew", "3rd", "3rd", "3rd", 
    "3rd", "Crew", "Crew", "3rd", "3rd", "3rd", "Crew", "Crew", "2nd", 
    "1st", "3rd", "1st", "1st", "3rd", "1st", "1st", "3rd", "Crew", 
    "3rd", "Crew", "Crew", "2nd", "Crew", "1st", "3rd", "3rd", "3rd", 
    "Crew", "Crew", "2nd", "3rd", "3rd", "3rd", "3rd", "3rd", "3rd", 
    "1st", "Crew", "3rd", "Crew", "3rd", "3rd", "3rd", "1st", "Crew", 
    "1st", "Crew", "3rd", "3rd", "1st", "3rd", "1st", "3rd", "Crew", 
    "2nd", "Crew", "2nd", "3rd", "Crew", "3rd", "1st", "Crew", "Crew", 
    "Crew", "2nd", "Crew", "3rd", "3rd", "Crew", "Crew", "2nd", "3rd", 
    "Crew", "2nd", "1st", "Crew", "3rd", "3rd", "3rd", "Crew", "Crew", 
    "3rd", "Crew", "3rd", "3rd", "Crew", "Crew", "1st", "Crew", "3rd", 
    "Crew", "1st", "3rd", "1st", "2nd", "2nd", "1st", "3rd", "3rd", 
    "3rd", "Crew", "Crew", "Crew", "Crew", "3rd", "Crew", "Crew", 
    "1st", "3rd", "3rd", "3rd", "1st", "Crew", "2nd", "Crew", "3rd", 
    "Crew", "Crew", "3rd", "Crew", "Crew", "Crew", "2nd", "3rd", 
    "1st", "Crew", "3rd", "Crew", "Crew", "Crew", "Crew", "2nd", 
    "Crew", "3rd", "Crew", "Crew", "Crew", "Crew", "3rd", "3rd", 
    "2nd", "3rd", "Crew", "3rd", "1st", "Crew", "3rd", "Crew", "Crew", 
    "3rd", "Crew", "3rd", "1st", "Crew", "3rd", "Crew", "Crew", "2nd", 
    "Crew", "3rd", "Crew", "3rd", "Crew", "Crew", "3rd", "Crew", 
    "Crew", "Crew", "3rd", "3rd", "3rd", "2nd", "1st", "2nd", "Crew", 
    "Crew", "2nd", "1st", "1st", "3rd", "Crew", "2nd", "2nd", "3rd", 
    "1st", "Crew", "Crew", "3rd", "Crew", "Crew", "1st", "2nd", "Crew", 
    "Crew", "Crew", "2nd", "Crew", "Crew", "3rd", "Crew", "3rd", 
    "2nd", "2nd", "1st", "2nd", "Crew", "3rd", "3rd", "Crew", "1st", 
    "Crew", "3rd", "Crew", "3rd", "Crew", "3rd", "Crew", "1st", "1st", 
    "Crew", "1st", "1st", "2nd", "3rd", "Crew", "Crew", "Crew", "Crew", 
    "3rd", "1st", "3rd", "1st", "3rd", "1st", "3rd", "2nd", "1st", 
    "Crew", "Crew", "Crew", "2nd", "1st", "Crew", "Crew", "Crew", 
    "3rd", "Crew", "3rd", "3rd", "3rd", "1st", "Crew", "Crew", "3rd", 
    "Crew", "3rd", "3rd", "3rd", "3rd", "3rd", "Crew", "Crew", "Crew", 
    "Crew", "Crew", "3rd", "Crew", "3rd", "2nd", "Crew", "Crew", 
    "Crew", "3rd", "2nd", "2nd", "2nd", "Crew", "2nd", "Crew", "2nd", 
    "3rd", "3rd", "Crew", "Crew", "1st", "Crew", "Crew", "3rd", "1st", 
    "Crew", "3rd", "3rd", "2nd", "3rd", "1st", "3rd", "2nd", "3rd", 
    "3rd", "Crew", "3rd", "2nd", "1st", "Crew", "2nd", "3rd", "1st", 
    "1st", "2nd", "Crew", "2nd", "Crew", "3rd", "3rd", "Crew", "Crew", 
    "Crew", "2nd", "Crew", "2nd", "2nd", "Crew", "Crew", "3rd", "1st", 
    "Crew", "Crew", "Crew", "3rd", "Crew", "Crew", "Crew", "2nd", 
    "3rd", "Crew", "3rd", "Crew", "1st", "3rd", "1st", "3rd", "Crew", 
    "Crew", "Crew", "2nd", "Crew", "3rd", "1st", "1st", "3rd", "3rd", 
    "Crew", "3rd", "3rd", "Crew", "1st", "Crew", "1st", "3rd", "1st", 
    "Crew", "Crew", "1st", "3rd", "Crew", "3rd", "Crew", "Crew", 
    "Crew", "Crew", "2nd", "3rd", "3rd", "2nd", "Crew", "Crew", "Crew", 
    "3rd", "3rd", "3rd", "1st", "3rd", "1st", "2nd", "Crew", "Crew", 
    "3rd", "Crew", "Crew", "1st", "Crew", "Crew", "3rd", "Crew", 
    "2nd", "3rd", "2nd", "Crew", "3rd", "3rd", "2nd", "3rd", "Crew", 
    "Crew", "Crew", "Crew", "3rd", "3rd", "3rd", "3rd", "2nd", "2nd", 
    "2nd", "1st", "1st", "1st", "2nd", "3rd", "2nd", "3rd", "3rd", 
    "Crew", "3rd", "3rd", "3rd", "Crew", "Crew", "Crew", "Crew", 
    "Crew", "3rd", "3rd", "Crew", "Crew", "Crew", "Crew", "3rd", 
    "2nd", "2nd", "2nd", "1st", "3rd", "3rd", "3rd", "3rd", "Crew", 
    "2nd", "3rd", "Crew", "Crew", "Crew", "2nd", "1st", "3rd", "Crew", 
    "Crew", "2nd", "Crew", "Crew", "Crew", "Crew", "Crew", "2nd", 
    "2nd", "2nd", "1st", "Crew", "3rd", "2nd", "3rd", "3rd", "3rd", 
    "Crew", "3rd", "3rd", "Crew", "2nd", "1st", "3rd", "3rd", "3rd", 
    "Crew", "2nd", "1st", "Crew", "Crew", "3rd", "2nd", "3rd", "Crew", 
    "Crew", "Crew", "Crew", "2nd", "2nd", "Crew", "2nd", "1st", "Crew", 
    "Crew", "3rd", "3rd", "3rd", "Crew", "Crew", "2nd", "1st", "3rd", 
    "Crew", "1st", "Crew", "3rd", "1st", "Crew", "Crew", "Crew", 
    "Crew", "Crew", "Crew", "3rd", "1st", "1st", "Crew", "Crew", 
    "Crew", "Crew", "Crew", "1st", "3rd", "Crew", "Crew", "Crew", 
    "Crew", "Crew", "3rd", "3rd", "Crew", "1st", "1st", "Crew"),
    titanic.sex =
    c("Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Female", "Female", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Female", "Female", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Female", "Female", "Female", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Female", "Female", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Female", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Female", "Male", "Female", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Female", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Female", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Female", "Male", "Female", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Female", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Female", "Female", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Female", "Female", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Female", "Male", "Female", 
    "Female", "Female", "Female", "Female", "Female", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Female", "Female", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Female", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Female", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Female", "Female", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Female", "Male", "Female", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Female", "Male", "Female", "Female", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Female", "Female", 
    "Female", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Female", "Male", "Female", "Male", "Male", "Female", 
    "Female", "Female", "Male", "Male", "Female", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Female", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Female", "Female", "Male", "Female", 
    "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Female", "Male", "Female", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Female", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Female", "Female", 
    "Female", "Female", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Female", "Male", "Female", 
    "Male", "Female", "Male", "Female", "Female", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Female", "Female", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Female", "Male", "Male", "Male", "Female", 
    "Male", "Female", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Female", "Female", "Male", "Male", "Male", "Female", 
    "Female", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Female", "Female", 
    "Male", "Female", "Male", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Female", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Female", "Male", 
    "Female", "Male", "Male", "Male", "Female", "Female", "Female", 
    "Female", "Male", "Female", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Female", "Female", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Female", "Female", "Male", 
    "Male", "Female", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Female", "Male", "Female", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Female", 
    "Female", "Female", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Female", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Female", 
    "Female", "Male", "Female", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Female", "Female", "Female", "Female", "Female", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Female", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Female", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Female", "Female", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Female", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Female", "Male", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Female", "Female", "Male", "Female", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Female", 
    "Female", "Male", "Male", "Female", "Female", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Female", "Male", "Female", "Female", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Female", 
    "Male", "Female", "Female", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Female", "Male", "Male", "Female", 
    "Male", "Male", "Female", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Female", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Female", "Female", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Female", "Male", "Female", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Female", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Female", "Female", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Female", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Female", "Male", "Male", "Male", "Male", "Female", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Female", 
    "Male", "Female", "Male", "Male", "Male", "Female", "Male", "Female", 
    "Male", "Male", "Male", "Female", "Female", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Female", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Female", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Female", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Female", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Female", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Female", "Male", "Male", 
    "Female", "Female", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Male", "Female", "Male", "Female", "Female", "Female", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Female", "Female", 
    "Female", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Female", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Female", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Female", "Male", "Female", "Male", 
    "Male", "Male", "Female", "Male", "Female", "Male", "Male", "Female", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Female", "Male", "Male", "Male", "Male", "Male", "Female", 
    "Male", "Female", "Male", "Female", "Male", "Male", "Male", "Male", 
    "Male", "Male", "Female", "Male", "Female", "Male", "Male", "Male", 
    "Male", "Male", "Male", "Male", "Male", "Female", "Male", "Male", 
    "Male", "Male", "Male", "Female", "Male", "Male", "Male", "Male"
    ),
    titanic.age =
    c("Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Child", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Child", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Child", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Child", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Child", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Child", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Child", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Child", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Child", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Child", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Child", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Child", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Child", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Child", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Child", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Child", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Child", "Adult", "Adult", "Adult", 
    "Adult", "Child", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Child", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Child", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Child", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Adult", "Child", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Child", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Child", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Child", "Adult", "Adult", "Adult", 
    "Child", "Child", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Child", "Adult", "Adult", "Child", "Adult", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Child", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Child", 
    "Child", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", "Adult", 
    "Adult", "Adult", "Adult"),
    titanic.survived =
    c(TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, 
    TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, 
    TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, 
    TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, 
    TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, 
    TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, 
    TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, 
    TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, 
    TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, 
    TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, 
    TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, 
    TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, 
    TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, 
    TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, 
    FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, 
    TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, 
    TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, 
    TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, 
    FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, 
    TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
    TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, 
    TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 
    TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, 
    TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, 
    TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 
    TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, 
    FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, 
    TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, 
    FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, 
    FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, 
    TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, 
    FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, 
    TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, 
    TRUE, TRUE, FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, 
    TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, 
    FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, TRUE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, 
    FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, 
    FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, 
    TRUE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE)
)

titanic_test <- function() {
  e <- get("e", parent.frame())
  source_result <- try(source(e$script_temp_path, local = new.env(), encoding = "UTF-8"), silent = TRUE)
  if (class(source_result)[1] == "try-error") return(FALSE)
  name.list <- paste0("answer", 1:6)
  answer1.ref <- .titanic.ref$titanic.class == "Crew"
  answer2.ref <- as.numeric(answer1.ref)
  answer3.ref <- sum(answer2.ref)
  answer4.ref <- sum(.titanic.ref$titanic.age == "Child")
  answer5.ref <- mean(!.titanic.ref$titanic.survived)
  answer6.ref <- mean(!.titanic.ref$titanic.survived[.titanic.ref$titanic.sex == "Male"])
  tryCatch({
    for(name in name.list) {
      if (!isTRUE(all.equal(
        get(name, envir = globalenv()),
        get(sprintf("%s.ref", name))
      ))) stop(sprintf("%s is wrong! Try again.\n", name))
    }
    TRUE
  }, error = function(e) {
    cat(conditionMessage(e))
    FALSE
  })  
}